### ISSUE TITLE
Inventory Click and Close error in other plugins

### ISSUE THREAD

**Issue by imBuzz** [masecla22/VillagerGUIApi#5]
Hi, today i used your plugin to create villagers inventories on my plugins, but when i used it a lot of plugins such as WorldGuard, EliteEnchantments, ShopGUIPlus created a lots of "errors" in console, and that's a lot of spam, do you know a way to fix this? I'm sending all screenshots to you.

https://gyazo.com/79f968e3bee79df739859679972bd0d9
https://gyazo.com/1664a3fc862062756513d9f3ae3ce3df
https://gyazo.com/678839c91525ab13ed5102cc1d92426e

**Comment by masecla22** [comment]
Could you show me how you open the inventories?
I feel like the plugins are trying to access an inventory that is open to the player, but that is not an actual villager.

**Comment by imBuzz** [comment]
Like your wiki, but you can close this issue, i've decided to change my plans ;)
